"""Initial tables

Revision ID: 64440b2d9589
Revises: 
Create Date: 2020-04-30 16:15:21.959069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64440b2d9589'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_id'), 'classification', ['id'], unique=False)
    op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['classification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_id'), 'ride', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_id'), table_name='ride')
    op.drop_table('ride')
    op.drop_index(op.f('ix_classification_id'), table_name='classification')
    op.drop_table('classification')
    # ### end Alembic commands ###
